package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val md_theme_light_primary = Color(0xFF005AC1)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD8E2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001A41)
val md_theme_light_secondary = Color(0xFF006C4C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF89F8C7)
val md_theme_light_onSecondaryContainer = Color(0xFF002114)
val md_theme_light_tertiary = Color(0xFFB91D1D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDAD6)
val md_theme_light_onTertiaryContainer = Color(0xFF410002)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44474F)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFFADC6FF)
val md_theme_dark_onPrimary = Color(0xFF002E69)
val md_theme_dark_primaryContainer = Color(0xFF004494)
val md_theme_dark_onPrimaryContainer = Color(0xFFD8E2FF)
val md_theme_dark_secondary = Color(0xFF6CDBAC)
val md_theme_dark_onSecondary = Color(0xFF003826)
val md_theme_dark_secondaryContainer = Color(0xFF005138)
val md_theme_dark_onSecondaryContainer = Color(0xFF89F8C7)
val md_theme_dark_tertiary = Color(0xFFFFB4AB)
val md_theme_dark_onTertiary = Color(0xFF690005)
val md_theme_dark_tertiaryContainer = Color(0xFF93000A)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD6)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF44474F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)

// Semantic Colors for Finance
val ExpenseColor = Color(0xFFE53935)
val IncomeColor = Color(0xFF43A047)
val TransferColor = Color(0xFF757575)
val ExpenseColorDark = Color(0xFFEF9A9A)
val IncomeColorDark = Color(0xFFA5D6A7)
val TransferColorDark = Color(0xFFBDBDBD)
